//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ThellierTool.rc
//
#define IDR_THELLITYPE_SRVR_IP          4
#define IDR_THELLITYPE_SRVR_EMB         5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_RESULTFORM_FORM             102
#define IDR_RESULTFORM_TMPL             103
#define IDR_MAINFRAME                   128
#define IDR_THELLITYPE                  129
#define IDD_CRITERIA_DIALOG             130
#define IDC_RAWDATA_LIST                1000
#define IDC_LABFIELD_EDIT               1001
#define IDC_SAMPLENAME_EDIT             1002
#define IDC_THELLIERPLOT_RADIO          1003
#define IDC_ZIJPLOT_RADIO               1004
#define IDC_DECAYPLOT_RADIO             1005
#define IDC_MDPLOT_RADIO                1006
#define IDC_ALLPLOTS_RADIO              1007
#define IDC_CORECO_RADIO                1008
#define IDC_GEOCO_RADIO                 1009
#define IDC_BEDCO_RADIO                 1010
#define IDC_AUTO_RADIO                  1011
#define IDC_MANUELL_RADIO               1012
#define IDC_TMIN_EDIT                   1013
#define IDC_TMAX_EDIT                   1014
#define IDC_APPLY_BUTTON                1015
#define IDC_AC_CHECK                    1016
#define IDC_CORR_CHECK                  1017
#define IDC_ZONLY_CHECK                 1018
#define IDC_PALINT_EDIT                 1019
#define IDC_SD_EDIT                     1020
#define IDC_N_EDIT                      1021
#define IDC_SLOPE_EDIT                  1022
#define IDC_STDSLOPE_EDIT               1023
#define IDC_CLASS_EDIT                  1024
#define IDC_F_EDIT                      1025
#define IDC_G_EDIT                      1026
#define IDC_Q_EDIT                      1027
#define IDC_W_EDIT                      1028
#define IDC_TRM_EDIT                    1029
#define IDC_NRMT_EDIT                   1030
#define IDC_CKERROR_EDIT                1031
#define IDC_CKDIFF_EDIT                 1032
#define IDC_DEC_EDIT                    1033
#define IDC_INC_EDIT                    1034
#define IDC_MDTAIL_LIST                 1035
#define IDC_MAD_EDIT                    1036
#define IDC_TYPE_EDIT                   1037
#define IDC_ACCHECK_EDIT                1038
#define IDC_SAVERESULTS_BUTTON          1039
#define IDC_TRERROR_EDIT                1040
#define IDC_N_CRIT_A_EDIT               1041
#define IDC_DEC_NA_EDIT                 1041
#define IDC_WEIGHT_W_RADIO              1042
#define IDC_INC_NA_EDIT                 1042
#define IDC_WEIGHT_Q_RADIO              1043
#define IDC_MAD_NA_EDIT                 1043
#define IDC_F_CRIT_A_EDIT               1044
#define IDC_STD_CRIT_A_EDIT             1045
#define IDC_Q_CRIT_A_EDIT               1046
#define IDC_CKERROR_CRIT_A_EDIT         1047
#define IDC_N_CRIT_B_EDIT               1048
#define IDC_MAD_CRIT_A_EDIT             1049
#define IDC_F_CRIT_B_EDIT               1050
#define IDC_STD_CRIT_B_EDIT             1051
#define IDC_Q_CRIT_B_EDIT               1052
#define IDC_CKERROR_CRIT_B_EDIT         1053
#define IDC_MAD_CRIT_B_EDIT             1054
#define IDC_CKDIFF_CRIT_A_EDIT          1055
#define IDC_HDIFF_CRIT_A_EDIT           1056
#define IDC_ZDIFF_CRIT_A_EDIT           1057
#define IDC_RDIFF_CRIT_A_EDIT           1058
#define IDC_ACERROR_CRIT_A_EDIT         1059
#define IDC_CKDIFF_CRIT_B_EDIT          1060
#define IDC_HDIFF_CRIT_B_EDIT           1061
#define IDC_ZDIFF_CRIT_B_EDIT           1062
#define IDC_RDIFF_CRIT_B_EDIT           1063
#define IDC_ACERROR_CRIT_B_EDIT         1064
#define IDC_MAD_AN_CRIT_A_EDIT          1065
#define IDC_MAD_AN_CRIT_B_EDIT          1066
#define IDC_NOTEPAD_BUTTON              1067
#define IDC_AUTOCK_YES_CHECK            1071
#define IDC_AUTOCK_CHECK                1072
#define IDC_TEST_BUTTON                 1073
#define IDC_ALPHA_EDIT                  1074
#define IDC_DRAT_EDIT                   1075
#define IDC_SEPAXES_RADIO               1075
#define IDC_EQUALAXES_RADIO             1076
#define IDC_TSTAR_EDIT                  1077
#define IDC_ALPHA_CRIT_B_EDIT           1078
#define IDC_DRAT_CRIT_A_EDIT            1079
#define IDC_DRAT_CRIT_B_EDIT            1080
#define IDC_ALPHA_CRIT_A_EDIT           1081
#define IDC_CRILOAD_BUTTON              1082
#define IDC_CRISAVE_BUTTON              1083
#define IDC_CRIPATH_EDIT                1085
#define IDC_CRIDEFAULT_BUTTON           1086
#define IDC_ALPHA_STATIC                1087
#define IDC_ALTCHECKMETHOD_EDIT         1088
#define IDC_ZDIFF_A_STATIC              1089
#define IDC_ZDIFF_B_STATIC              1090
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_CRITERIA                     32774
#define ID_HELP_MANUALPDF               32776
#define ID_FILE_SAVEGRAPH               32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
